# Generated by Django 5.2.1 on 2025-05-16 18:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pracownik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imie_nazwisko', models.CharField(max_length=100)),
                ('stanowisko', models.CharField(max_length=50)),
                ('instytut', models.CharField(max_length=50)),
                ('katedra', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Pracownik',
                'verbose_name_plural': 'Pracownicy',
            },
        ),
        migrations.CreateModel(
            name='Przedmiot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('czy_do_wyboru', models.BooleanField()),
                ('nazwa', models.CharField(max_length=200, unique=True)),
                ('sem', models.IntegerField()),
                ('ects', models.IntegerField()),
                ('instytut', models.CharField(max_length=50)),
                ('katedra', models.CharField(max_length=50)),
                ('poziom', models.CharField(choices=[('I', 'I'), ('II', 'II'), ('III', 'III'), ('JM', 'JM')], max_length=3)),
                ('specjalizacja', models.CharField(blank=True, max_length=50, null=True)),
                ('lokalizacja', models.CharField(max_length=50)),
                ('jezyk', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'Przedmiot',
                'verbose_name_plural': 'Przedmioty',
            },
        ),
        migrations.CreateModel(
            name='RokAkademicki',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rok', models.CharField(help_text='Format RRRR/RRRR', max_length=9, unique=True)),
            ],
            options={
                'verbose_name': 'Rok akademicki',
                'verbose_name_plural': 'Lata akademickie',
            },
        ),
        migrations.CreateModel(
            name='Grupa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grupa', models.CharField(max_length=20, unique=True)),
                ('kierunek', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Grupa',
                'verbose_name_plural': 'Grupy',
                'constraints': [models.UniqueConstraint(fields=('grupa', 'kierunek'), name='unikalna_grupa_na_kierunku')],
            },
        ),
        migrations.CreateModel(
            name='PrzedmiotRok',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forma_zaliczenia', models.CharField(blank=True, max_length=20, null=True)),
                ('liczba_godz', models.IntegerField()),
                ('forma_zajec', models.CharField(choices=[('ĆW', 'ĆW'), ('LB', 'LB'), ('W', 'W'), ('K', 'K'), ('S', 'S')], max_length=2)),
                ('rodzaj', models.CharField(choices=[('S', 'S'), ('NZ', 'NZ')], max_length=2)),
                ('rok_ob', models.IntegerField(blank=True, null=True)),
                ('ilosc_st_na_sem', models.IntegerField(blank=True, null=True)),
                ('liczba_godz_obc', models.IntegerField()),
                ('uwagi', models.TextField(blank=True, null=True)),
                ('czy_przed_wyborem', models.BooleanField(blank=True, null=True)),
                ('grupa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.grupa')),
                ('koordynator_sylabusa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='koordynowane_sylabusy', to='core.pracownik')),
                ('prowadzacy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prowadzone_przedmioty', to='core.pracownik')),
                ('przedmiot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.przedmiot')),
                ('rok_akademicki', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.rokakademicki')),
            ],
            options={
                'verbose_name': 'Realizacja przedmiotu w roku',
                'verbose_name_plural': 'Realizacje przedmiotów w latach',
            },
        ),
        migrations.CreateModel(
            name='PracownikRok',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pensum_stanowisko', models.FloatField()),
                ('pensum_pracownika', models.FloatField()),
                ('inne_godz', models.FloatField(blank=True, null=True)),
                ('obciazenie', models.FloatField()),
                ('pracownik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roczne_dane', to='core.pracownik')),
                ('rok_akademicki', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dane_pracownikow_w_roku', to='core.rokakademicki')),
            ],
            options={
                'verbose_name': 'Dane roczne pracownika',
                'verbose_name_plural': 'Dane roczne pracowników',
                'constraints': [models.UniqueConstraint(fields=('pracownik', 'rok_akademicki'), name='unikalne_dane_pracownika_na_rok')],
            },
        ),
    ]
